site_name: MADDev - Documentation
theme:
  name: material

nav: [
        "home": "index.html",
        "Atas": [
          "atas/reuniao01.md"
        ],
        "Elicitacao": [
          "elicitacao/mvp1.md",
          "elicitacao/brainstorm.md",
          "elicitacao/backlog.md"
        ],
        "GameJam": [
          "gamejam/gamejam-goiania.md"
        ],
]
