site_name: MADDev - Documentation
theme:
  name: mkdocs

nav:
  - Home: "index.html"
  - Steve is Alone: steveIsAlone/index.html
  - Fragmento: fragmento/index.html
  - Death Roll: deathRoll/index.html
